/* Auto-generated by genmsg_cpp for file /home/parallels/groovy_workspace/oryx_srr/oryx_drive_controller/msg/VelocityArc.msg */
#ifndef ORYX_DRIVE_CONTROLLER_MESSAGE_VELOCITYARC_H
#define ORYX_DRIVE_CONTROLLER_MESSAGE_VELOCITYARC_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace oryx_drive_controller
{
template <class ContainerAllocator>
struct VelocityArc_ {
  typedef VelocityArc_<ContainerAllocator> Type;

  VelocityArc_()
  : velocity(0.0)
  , radius(0.0)
  {
  }

  VelocityArc_(const ContainerAllocator& _alloc)
  : velocity(0.0)
  , radius(0.0)
  {
  }

  typedef double _velocity_type;
  double velocity;

  typedef double _radius_type;
  double radius;


  typedef boost::shared_ptr< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oryx_drive_controller::VelocityArc_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct VelocityArc
typedef  ::oryx_drive_controller::VelocityArc_<std::allocator<void> > VelocityArc;

typedef boost::shared_ptr< ::oryx_drive_controller::VelocityArc> VelocityArcPtr;
typedef boost::shared_ptr< ::oryx_drive_controller::VelocityArc const> VelocityArcConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::oryx_drive_controller::VelocityArc_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace oryx_drive_controller

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::oryx_drive_controller::VelocityArc_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a4769d0b94d27fd4f9e32c14097aeebb";
  }

  static const char* value(const  ::oryx_drive_controller::VelocityArc_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa4769d0b94d27fd4ULL;
  static const uint64_t static_value2 = 0xf9e32c14097aeebbULL;
};

template<class ContainerAllocator>
struct DataType< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "oryx_drive_controller/VelocityArc";
  }

  static const char* value(const  ::oryx_drive_controller::VelocityArc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Service used to send velocity-radius information to the ArcDriveController\n\
\n\
#Tangential Velocity To Maintain\n\
float64 velocity\n\
\n\
#Radius of arc to create\n\
float64 radius\n\
\n\
";
  }

  static const char* value(const  ::oryx_drive_controller::VelocityArc_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.velocity);
    stream.next(m.radius);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct VelocityArc_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oryx_drive_controller::VelocityArc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::oryx_drive_controller::VelocityArc_<ContainerAllocator> & v) 
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORYX_DRIVE_CONTROLLER_MESSAGE_VELOCITYARC_H

