/* Auto-generated by genmsg_cpp for file /home/parallels/fuerte_workspace/oryxssr/oryxsrr_msgs/msg/OccupancyGrid.msg */
#ifndef ORYXSRR_MSGS_MESSAGE_OCCUPANCYGRID_H
#define ORYXSRR_MSGS_MESSAGE_OCCUPANCYGRID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"
#include "sensor_msgs/PointCloud2.h"

namespace oryxsrr_msgs
{
template <class ContainerAllocator>
struct OccupancyGrid_ {
  typedef OccupancyGrid_<ContainerAllocator> Type;

  OccupancyGrid_()
  : header()
  , xDim(0.0)
  , yDim(0.0)
  , zDim(0.0)
  , res(0.0)
  , origin()
  , cloud()
  {
  }

  OccupancyGrid_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , xDim(0.0)
  , yDim(0.0)
  , zDim(0.0)
  , res(0.0)
  , origin(_alloc)
  , cloud(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _xDim_type;
  double xDim;

  typedef double _yDim_type;
  double yDim;

  typedef double _zDim_type;
  double zDim;

  typedef double _res_type;
  double res;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _origin_type;
   ::geometry_msgs::Point_<ContainerAllocator>  origin;

  typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _cloud_type;
   ::sensor_msgs::PointCloud2_<ContainerAllocator>  cloud;


  typedef boost::shared_ptr< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct OccupancyGrid
typedef  ::oryxsrr_msgs::OccupancyGrid_<std::allocator<void> > OccupancyGrid;

typedef boost::shared_ptr< ::oryxsrr_msgs::OccupancyGrid> OccupancyGridPtr;
typedef boost::shared_ptr< ::oryxsrr_msgs::OccupancyGrid const> OccupancyGridConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace oryxsrr_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3f5d31d7c64f748d5ceddcd94f26d6b8";
  }

  static const char* value(const  ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3f5d31d7c64f748dULL;
  static const uint64_t static_value2 = 0x5ceddcd94f26d6b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "oryxsrr_msgs/OccupancyGrid";
  }

  static const char* value(const  ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "#Header\n\
Header header\n\
\n\
#Information about the size of the occupancy grid\n\
float64 xDim\n\
float64 yDim\n\
float64 zDim\n\
float64 res\n\
\n\
#the origin of the grid\n\
geometry_msgs/Point origin\n\
\n\
#The PointCloud which backs the occupancy grid\n\
sensor_msgs/PointCloud2 cloud\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointCloud2\n\
# This message holds a collection of N-dimensional points, which may\n\
# contain additional information such as normals, intensity, etc. The\n\
# point data is stored as a binary blob, its layout described by the\n\
# contents of the \"fields\" array.\n\
\n\
# The point cloud data may be organized 2d (image-like) or 1d\n\
# (unordered). Point clouds organized as 2d images may be produced by\n\
# camera depth sensors such as stereo or time-of-flight.\n\
\n\
# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n\
# points).\n\
Header header\n\
\n\
# 2D structure of the point cloud. If the cloud is unordered, height is\n\
# 1 and width is the length of the point cloud.\n\
uint32 height\n\
uint32 width\n\
\n\
# Describes the channels and their layout in the binary data blob.\n\
PointField[] fields\n\
\n\
bool    is_bigendian # Is this data bigendian?\n\
uint32  point_step   # Length of a point in bytes\n\
uint32  row_step     # Length of a row in bytes\n\
uint8[] data         # Actual point data, size is (row_step*height)\n\
\n\
bool is_dense        # True if there are no invalid points\n\
\n\
================================================================================\n\
MSG: sensor_msgs/PointField\n\
# This message holds the description of one point entry in the\n\
# PointCloud2 message format.\n\
uint8 INT8    = 1\n\
uint8 UINT8   = 2\n\
uint8 INT16   = 3\n\
uint8 UINT16  = 4\n\
uint8 INT32   = 5\n\
uint8 UINT32  = 6\n\
uint8 FLOAT32 = 7\n\
uint8 FLOAT64 = 8\n\
\n\
string name      # Name of field\n\
uint32 offset    # Offset from start of point struct\n\
uint8  datatype  # Datatype enumeration, see above\n\
uint32 count     # How many elements in the field\n\
\n\
";
  }

  static const char* value(const  ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.xDim);
    stream.next(m.yDim);
    stream.next(m.zDim);
    stream.next(m.res);
    stream.next(m.origin);
    stream.next(m.cloud);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OccupancyGrid_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::oryxsrr_msgs::OccupancyGrid_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xDim: ";
    Printer<double>::stream(s, indent + "  ", v.xDim);
    s << indent << "yDim: ";
    Printer<double>::stream(s, indent + "  ", v.yDim);
    s << indent << "zDim: ";
    Printer<double>::stream(s, indent + "  ", v.zDim);
    s << indent << "res: ";
    Printer<double>::stream(s, indent + "  ", v.res);
    s << indent << "origin: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    s << indent << "cloud: ";
s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.cloud);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORYXSRR_MSGS_MESSAGE_OCCUPANCYGRID_H

