/* Auto-generated by genmsg_cpp for file /home/oryx/ros_workspace/Oryx/OryxMessages/msg/Battery.msg */
#ifndef ORYXMESSAGES_MESSAGE_BATTERY_H
#define ORYXMESSAGES_MESSAGE_BATTERY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace OryxMessages
{
template <class ContainerAllocator>
struct Battery_ {
  typedef Battery_<ContainerAllocator> Type;

  Battery_()
  : node(0)
  , voltage(0.0)
  {
  }

  Battery_(const ContainerAllocator& _alloc)
  : node(0)
  , voltage(0.0)
  {
  }

  typedef int16_t _node_type;
  int16_t node;

  typedef float _voltage_type;
  float voltage;


private:
  static const char* __s_getDataType_() { return "OryxMessages/Battery"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "2d1e860aa474f2b66bc671e6980bbd27"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int16 node\n\
float32 voltage\n\
\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, node);
    ros::serialization::serialize(stream, voltage);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, node);
    ros::serialization::deserialize(stream, voltage);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(node);
    size += ros::serialization::serializationLength(voltage);
    return size;
  }

  typedef boost::shared_ptr< ::OryxMessages::Battery_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::OryxMessages::Battery_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Battery
typedef  ::OryxMessages::Battery_<std::allocator<void> > Battery;

typedef boost::shared_ptr< ::OryxMessages::Battery> BatteryPtr;
typedef boost::shared_ptr< ::OryxMessages::Battery const> BatteryConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::OryxMessages::Battery_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::OryxMessages::Battery_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace OryxMessages

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::OryxMessages::Battery_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::OryxMessages::Battery_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::OryxMessages::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2d1e860aa474f2b66bc671e6980bbd27";
  }

  static const char* value(const  ::OryxMessages::Battery_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2d1e860aa474f2b6ULL;
  static const uint64_t static_value2 = 0x6bc671e6980bbd27ULL;
};

template<class ContainerAllocator>
struct DataType< ::OryxMessages::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "OryxMessages/Battery";
  }

  static const char* value(const  ::OryxMessages::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::OryxMessages::Battery_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 node\n\
float32 voltage\n\
\n\
\n\
";
  }

  static const char* value(const  ::OryxMessages::Battery_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::OryxMessages::Battery_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::OryxMessages::Battery_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.node);
    stream.next(m.voltage);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Battery_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::OryxMessages::Battery_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::OryxMessages::Battery_<ContainerAllocator> & v) 
  {
    s << indent << "node: ";
    Printer<int16_t>::stream(s, indent + "  ", v.node);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORYXMESSAGES_MESSAGE_BATTERY_H

