/* Auto-generated by genmsg_cpp for file /home/oryx/ros_workspace/Oryx/OryxMessages/msg/Temperature.msg */
#ifndef ORYXMESSAGES_MESSAGE_TEMPERATURE_H
#define ORYXMESSAGES_MESSAGE_TEMPERATURE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace OryxMessages
{
template <class ContainerAllocator>
struct Temperature_ {
  typedef Temperature_<ContainerAllocator> Type;

  Temperature_()
  : temperature_node(0)
  , temperature(0.0)
  , warning_Temp(0.0)
  , danger_Temp(0.0)
  {
  }

  Temperature_(const ContainerAllocator& _alloc)
  : temperature_node(0)
  , temperature(0.0)
  , warning_Temp(0.0)
  , danger_Temp(0.0)
  {
  }

  typedef int32_t _temperature_node_type;
  int32_t temperature_node;

  typedef float _temperature_type;
  float temperature;

  typedef float _warning_Temp_type;
  float warning_Temp;

  typedef float _danger_Temp_type;
  float danger_Temp;


private:
  static const char* __s_getDataType_() { return "OryxMessages/Temperature"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e62c9d14f34e94252b4cc03e1d4997da"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "int32 temperature_node\n\
float32 temperature\n\
float32 warning_Temp\n\
float32 danger_Temp\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, temperature_node);
    ros::serialization::serialize(stream, temperature);
    ros::serialization::serialize(stream, warning_Temp);
    ros::serialization::serialize(stream, danger_Temp);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, temperature_node);
    ros::serialization::deserialize(stream, temperature);
    ros::serialization::deserialize(stream, warning_Temp);
    ros::serialization::deserialize(stream, danger_Temp);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(temperature_node);
    size += ros::serialization::serializationLength(temperature);
    size += ros::serialization::serializationLength(warning_Temp);
    size += ros::serialization::serializationLength(danger_Temp);
    return size;
  }

  typedef boost::shared_ptr< ::OryxMessages::Temperature_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::OryxMessages::Temperature_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Temperature
typedef  ::OryxMessages::Temperature_<std::allocator<void> > Temperature;

typedef boost::shared_ptr< ::OryxMessages::Temperature> TemperaturePtr;
typedef boost::shared_ptr< ::OryxMessages::Temperature const> TemperatureConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::OryxMessages::Temperature_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::OryxMessages::Temperature_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace OryxMessages

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::OryxMessages::Temperature_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::OryxMessages::Temperature_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::OryxMessages::Temperature_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e62c9d14f34e94252b4cc03e1d4997da";
  }

  static const char* value(const  ::OryxMessages::Temperature_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe62c9d14f34e9425ULL;
  static const uint64_t static_value2 = 0x2b4cc03e1d4997daULL;
};

template<class ContainerAllocator>
struct DataType< ::OryxMessages::Temperature_<ContainerAllocator> > {
  static const char* value() 
  {
    return "OryxMessages/Temperature";
  }

  static const char* value(const  ::OryxMessages::Temperature_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::OryxMessages::Temperature_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 temperature_node\n\
float32 temperature\n\
float32 warning_Temp\n\
float32 danger_Temp\n\
\n\
";
  }

  static const char* value(const  ::OryxMessages::Temperature_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::OryxMessages::Temperature_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::OryxMessages::Temperature_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.temperature_node);
    stream.next(m.temperature);
    stream.next(m.warning_Temp);
    stream.next(m.danger_Temp);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Temperature_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::OryxMessages::Temperature_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::OryxMessages::Temperature_<ContainerAllocator> & v) 
  {
    s << indent << "temperature_node: ";
    Printer<int32_t>::stream(s, indent + "  ", v.temperature_node);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "warning_Temp: ";
    Printer<float>::stream(s, indent + "  ", v.warning_Temp);
    s << indent << "danger_Temp: ";
    Printer<float>::stream(s, indent + "  ", v.danger_Temp);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ORYXMESSAGES_MESSAGE_TEMPERATURE_H

