/* Auto-generated by genmsg_cpp for file /home/parallels/fuerte_workspace/oryxssr/EposManager/msg/GroupEPOSControl.msg */
#ifndef EPOSMANAGER_MESSAGE_GROUPEPOSCONTROL_H
#define EPOSMANAGER_MESSAGE_GROUPEPOSCONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "EposManager/EPOSControl.h"

namespace EposManager
{
template <class ContainerAllocator>
struct GroupEPOSControl_ {
  typedef GroupEPOSControl_<ContainerAllocator> Type;

  GroupEPOSControl_()
  : motor_group()
  {
  }

  GroupEPOSControl_(const ContainerAllocator& _alloc)
  : motor_group(_alloc)
  {
  }

  typedef std::vector< ::EposManager::EPOSControl_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::EposManager::EPOSControl_<ContainerAllocator> >::other >  _motor_group_type;
  std::vector< ::EposManager::EPOSControl_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::EposManager::EPOSControl_<ContainerAllocator> >::other >  motor_group;


  typedef boost::shared_ptr< ::EposManager::GroupEPOSControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::EposManager::GroupEPOSControl_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GroupEPOSControl
typedef  ::EposManager::GroupEPOSControl_<std::allocator<void> > GroupEPOSControl;

typedef boost::shared_ptr< ::EposManager::GroupEPOSControl> GroupEPOSControlPtr;
typedef boost::shared_ptr< ::EposManager::GroupEPOSControl const> GroupEPOSControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::EposManager::GroupEPOSControl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::EposManager::GroupEPOSControl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace EposManager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::EposManager::GroupEPOSControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::EposManager::GroupEPOSControl_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::EposManager::GroupEPOSControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "58778ccf9bb7db6f7ccd5eaa3d10b6d8";
  }

  static const char* value(const  ::EposManager::GroupEPOSControl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x58778ccf9bb7db6fULL;
  static const uint64_t static_value2 = 0x7ccd5eaa3d10b6d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::EposManager::GroupEPOSControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "EposManager/GroupEPOSControl";
  }

  static const char* value(const  ::EposManager::GroupEPOSControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::EposManager::GroupEPOSControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This represents a control structure for a Maxon motor attached to an EPOS 2 controller.  \n\
# The node_id is the node_id set on the epos controller itself\n\
# The control_mode corresponds with the desired mode of control\n\
# The setpoint corresponds with the desired value for the selected mode\n\
\n\
EPOSControl[] motor_group\n\
\n\
================================================================================\n\
MSG: EposManager/EPOSControl\n\
# This represents a control structure for a Maxon motor attached to an EPOS 2 controller.  \n\
# The node_id is the node_id set on the epos controller itself\n\
# The control_mode corresponds with the desired mode of control\n\
# The setpoint corresponds with the desired value for the selected mode\n\
\n\
# Control Mode Options\n\
uint8 VELOCITY =1\n\
uint8 ABSOLUTE_POSITION = 2\n\
uint8 ABSOLUTE_POSITION_IMMEDIATE = 3\n\
uint8 RELATIVE_POSITION = 4\n\
uint8 RELATIVE_POSITION_IMMEDIATE = 5\n\
\n\
\n\
uint16 node_id\n\
uint8 control_mode\n\
int32 setpoint\n\
\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const  ::EposManager::GroupEPOSControl_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::EposManager::GroupEPOSControl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.motor_group);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GroupEPOSControl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::EposManager::GroupEPOSControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::EposManager::GroupEPOSControl_<ContainerAllocator> & v) 
  {
    s << indent << "motor_group[]" << std::endl;
    for (size_t i = 0; i < v.motor_group.size(); ++i)
    {
      s << indent << "  motor_group[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::EposManager::EPOSControl_<ContainerAllocator> >::stream(s, indent + "    ", v.motor_group[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // EPOSMANAGER_MESSAGE_GROUPEPOSCONTROL_H

