/* Auto-generated by genmsg_cpp for file /home/parallels/fuerte_workspace/oryxssr/EposManager/msg/GroupMotorInfo.msg */
#ifndef EPOSMANAGER_MESSAGE_GROUPMOTORINFO_H
#define EPOSMANAGER_MESSAGE_GROUPMOTORINFO_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "EposManager/MotorInfo.h"

namespace EposManager
{
template <class ContainerAllocator>
struct GroupMotorInfo_ {
  typedef GroupMotorInfo_<ContainerAllocator> Type;

  GroupMotorInfo_()
  : motor_group()
  {
  }

  GroupMotorInfo_(const ContainerAllocator& _alloc)
  : motor_group(_alloc)
  {
  }

  typedef std::vector< ::EposManager::MotorInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::EposManager::MotorInfo_<ContainerAllocator> >::other >  _motor_group_type;
  std::vector< ::EposManager::MotorInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::EposManager::MotorInfo_<ContainerAllocator> >::other >  motor_group;


  typedef boost::shared_ptr< ::EposManager::GroupMotorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::EposManager::GroupMotorInfo_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GroupMotorInfo
typedef  ::EposManager::GroupMotorInfo_<std::allocator<void> > GroupMotorInfo;

typedef boost::shared_ptr< ::EposManager::GroupMotorInfo> GroupMotorInfoPtr;
typedef boost::shared_ptr< ::EposManager::GroupMotorInfo const> GroupMotorInfoConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::EposManager::GroupMotorInfo_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::EposManager::GroupMotorInfo_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace EposManager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::EposManager::GroupMotorInfo_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::EposManager::GroupMotorInfo_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::EposManager::GroupMotorInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "df4d06ffe0935e1bb3f70b2d4bb7a274";
  }

  static const char* value(const  ::EposManager::GroupMotorInfo_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdf4d06ffe0935e1bULL;
  static const uint64_t static_value2 = 0xb3f70b2d4bb7a274ULL;
};

template<class ContainerAllocator>
struct DataType< ::EposManager::GroupMotorInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "EposManager/GroupMotorInfo";
  }

  static const char* value(const  ::EposManager::GroupMotorInfo_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::EposManager::GroupMotorInfo_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# This represents the motor information of a group of motors\n\
\n\
MotorInfo[] motor_group\n\
\n\
================================================================================\n\
MSG: EposManager/MotorInfo\n\
# This represents the motor information of a specific motor\n\
# node_id is the node_id set on the EPOS Controller itself\n\
# motor_name is the name of the motor, as assigned by the user\n\
# enabled indicated whether or not the motor is enabled or disabled\n\
# motor_mode is the mode the motor is in (velocity, position, current)\n\
# motor_velocity is the velocity of the motor in rpm\n\
# motor_position is the position of the motor in encoder counts\n\
# motor_current is the current on the motor in milliamps\n\
\n\
uint16 node_id\n\
string motor_name\n\
uint16 state\n\
string faults\n\
int32 motor_velocity\n\
int32 motor_position\n\
int32 motor_current\n\
time stamp\n\
\n\
";
  }

  static const char* value(const  ::EposManager::GroupMotorInfo_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::EposManager::GroupMotorInfo_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.motor_group);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GroupMotorInfo_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::EposManager::GroupMotorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::EposManager::GroupMotorInfo_<ContainerAllocator> & v) 
  {
    s << indent << "motor_group[]" << std::endl;
    for (size_t i = 0; i < v.motor_group.size(); ++i)
    {
      s << indent << "  motor_group[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::EposManager::MotorInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.motor_group[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // EPOSMANAGER_MESSAGE_GROUPMOTORINFO_H

