<?xml version="1.0"?>
<robot 
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
	xmlns:xacro="http://ros.org/wiki/xacro" name="aero">
       
  <!-- Included URDF/XACRO Files -->
  <include filename="$(find aero_description)/urdf/husky.urdf.xacro" />
  <include filename="$(find aero_description)/urdf/stereo_camera_pair.urdf.xacro" />
  <include filename="$(find aero_description)/urdf/sick_laser.urdf.xacro" />
  <include filename="$(find aero_description)/urdf/simple_transform.urdf.xacro" />
  <include filename="$(find aero_description)/urdf/simple_transform.urdf.xacro" />
  <include filename="$(find jaco_model)/urdf/jaco_arm.xacro" />

  <property name="boom_length" value="1.085" />
  <property name="boom_diameter" value="0.0538" />



  <xacro:husky/>  

  <!-- Boom -->
  <xacro:static_transform parent="top_plate" name="boom_base" xyz="-0.23 0 0.0762" rpy="0 0 0">
    <visual>
      <origin xyz="0 0 -0.02" rpy="0 0 0" />
      <geometry>
	<box size="0.05 0.05 0.05" />
      </geometry>
      <material name="Blue" />
    </visual>
  </xacro:static_transform>
  <xacro:revolute_pan_transform parent="boom_base" name="boom" xyz="0 0 0" rpy="0 0 0" lower_limit="-2" upper_limit="2">
    <visual>
      <origin xyz="0.0 0.0 ${boom_length/2}" rpy="0 0 0" />
      <geometry>
	<cylinder length="${boom_length}" radius="${boom_diameter/2}" />
      </geometry>
      <material name="Black" />
    </visual>
  </xacro:revolute_pan_transform>
  <xacro:static_transform parent="boom" name="boom_top" xyz="0 0 ${boom_length}" rpy="0 0 0">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="0.00 0.00 0.00" />
      </geometry>
    </visual>
  </xacro:static_transform>



  <!-- Cameras -->
  <xacro:stereo_camera_pair parent="boom_top" prefix="upper_stereo" xyz="0 0 0.005" rpy="0 0 0" camera_base_length="0.3" camera_tilt="${13*M_PI/180}"/>
  <xacro:stereo_camera_pair parent="boom_top" prefix="lower_stereo" xyz="0 0 -0.127" rpy="0 0 0" camera_base_length="0.11" camera_tilt="${32*M_PI/180}"/>



  <!-- Laser -->
  <xacro:sick_laser_v0 name="laser" parent="base_link" ros_topic="laser" update_rate="25" >
    <origin xyz="${base_length/2+0.0635} 0 0.0254" rpy="${M_PI} 0 0" />
  </xacro:sick_laser_v0> 





  <!-- Arm -->
  <xacro:static_transform parent="base_link" name="arm_mount" xyz="0.325374 0 0.0826" rpy="0 0 0">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="0.01 0.01 0.01" />
      </geometry>
      <material name="Blue" />
    </visual>
  </xacro:static_transform>
  <xacro:static_transform parent="arm_mount" name="arm_base" xyz="0 0 0" rpy="0 0 ${-M_PI/2}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="0.01 0.01 0.01" />
      </geometry>
      <material name="Blue" />
    </visual>
  </xacro:static_transform>
<xacro:jaco_arm  parent="arm_base"/>


  <!-- IMU -->
  <xacro:static_transform parent="base_link" name="imu" xyz="0 0 0" rpy="0 ${-M_PI/2} ${-3*M_PI/4}">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="0.01 0.01 0.01" />
      </geometry>
      <material name="Blue" />
    </visual>
  </xacro:static_transform>

  
</robot>
