<?xml version="1.0"?>
<!--
Copyright (c) 2012, Siddhant Ahuja (Sid), Ryan Gariepy
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of Clearpath Robotics nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

This program contains the description of the robot base model for the Clearpath 
Husky A200
-->

<root 
	xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
	xmlns:xacro="http://ros.org/wiki/xacro" name="aero">
       
  <!-- Colors -->
  <material name="Black">
    <color rgba="0.0 0.0 0.0 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.0 0.0 0.8 1.0"/>
  </material>

  <material name="Green">
    <color rgba="0.0 0.8 0.0 1.0"/>
  </material>

  <material name="Gray">
    <color rgba="0.7 0.7 0.7 1.0"/>
  </material>

  <material name="DarkGray">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="White">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>
  
  <material name="Yellow">
    <color rgba="0.8 0.8 0.0 1.0"/>
  </material>

  <!-- PROPERTY LIST -->
  <!--All units in m-kg-s-radians unit system -->
  <property name="M_PI" value="3.1415926535897931" />



  <property name="base_length" value="0.806" />
  <property name="base_width" value="0.419" />
  <property name="base_height" value="0.228" />

  <property name="wheel_diameter" value="0.32" />
  <property name="wheel_width" value="0.11" />
  <property name="wheel_base_width" value="0.546" />
  <property name="wheel_base_length" value="0.558" />
  <property name="wheel_base_link_height" value="0.0381" />

  <property name="top_plate_length" value="0.549" />



  <xacro:macro name="husky_wheel" params="fb lr parent translateX translateY flipY"> <!--fb : front, back ; lr: left, right -->
    <link name="${fb}_${lr}_wheel">
      <visual>
	<origin xyz="0 0 0" rpy="${flipY*M_PI + M_PI/2} 0 0" /> 
	<geometry>
	  <cylinder radius="${wheel_diameter/2}" length="${wheel_width}" />
	</geometry>
	<material name="DarkGray" />
      </visual>
    </link>

    <joint name="joint_${fb}_${lr}_wheel" type="continuous">
      <parent link="${parent}"/>
      <child link="${fb}_${lr}_wheel"/>
      <origin xyz="${translateX * wheel_base_length/2} ${translateY * wheel_base_width/2} ${wheel_base_link_height}" rpy="0 0 0" /> 
      <axis xyz="0 1 0" rpy="0 0 0" />
      <limit effort="100" velocity="100"/>
      <joint_properties damping="0.0" friction="0.0"/>
    </joint>
  </xacro:macro>



  <xacro:macro name="husky">
    <link name="base_footprint">
      <visual>
	<origin xyz="0 0 0" rpy="0 0 0" />
	<geometry>
	  <box size="0.001 0.001 0.001" />
	</geometry>
	<material name="Blue" />
      </visual>
    </link>

  <xacro:static_transform parent="base_footprint" name="base_link" xyz="0 0 ${wheel_diameter/2-wheel_base_link_height}" rpy="0 0 0">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
      <geometry>
	<box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="Yellow" />
    </visual>
  </xacro:static_transform>

  <xacro:static_transform parent="base_link" name="top_plate" xyz="0 0 ${base_height}" rpy="0 0 0">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
	<box size="${top_plate_length} ${base_width} 0.02" />
      </geometry>
      <material name="DarkGray" />
    </visual>
  </xacro:static_transform>


    <!-- WHEEL macros -->
    <husky_wheel fb="back" lr="left" parent="base_link" translateX="-1" translateY="1" flipY="-1"/>
    <husky_wheel fb="back" lr="right" parent="base_link" translateX="-1" translateY="-1" flipY="-1"/>
    <husky_wheel fb="front" lr="left" parent="base_link" translateX="1" translateY="1" flipY="-1"/>
    <husky_wheel fb="front" lr="right" parent="base_link" translateX="1" translateY="-1" flipY="-1"/>

  </xacro:macro>


</root>
