<?xml version="1.0"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
      xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
      xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
      xmlns:xacro="http://ros.org/wiki/xacro">

  <include filename="$(find aero_description)/urdf/simple_transform.urdf.xacro" />
  <include filename="$(find aero_description)/urdf/manta_camera.urdf.xacro" />

  <xacro:macro name="stereo_camera_pair" params="prefix parent xyz rpy camera_offset">
    <link name="${prefix}/camera_rail"/>
    <joint name="${prefix}/joint_camera_rail" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}/camera_rail"/>
      <origin xyz="${xyz}" rpy="${rpy}" />
    </joint>

    <xacro:manta_cam_v0 frame_name="${prefix}/left_camera" parent="${prefix}/camera_rail" camera_name="${prefix}/left">
      <origin xyz="0.0 ${camera_offset/2} 0.0" rpy="0 0 0" />
    </xacro:manta_cam_v0> 
    
    <xacro:manta_cam_v0 frame_name="${prefix}/right_camera" parent="${prefix}/camera_rail" camera_name="${prefix}/right">
      <origin xyz="0.0 ${-camera_offset/2} 0.0" rpy="0 0 0" />
    </xacro:manta_cam_v0> 

    <xacro:static_transform parent="${prefix}/camera_rail" name="${prefix}/optical_frame" xyz="0 0 0" rpy="0 0 0"/>

  </xacro:macro>
  
</root>
