<?xml version="1.0" encoding="utf-8"?>
<root xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
      xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
      xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
      xmlns:xacro="http://ros.org/wiki/xacro">

  <include filename="$(find aero_description)/urdf/simple_transform.urdf.xacro" />
  <include filename="$(find aero_description)/urdf/manta_camera.urdf.xacro" />

  <xacro:macro name="stereo_camera_pair" params="prefix parent xyz rpy camera_offset">
    <xacro:static_transform parent="${parent}" name="${prefix}/camera_rail" xyz="${xyz}" rpy="${rpy}">
    <visual>
      <origin xyz="-0.03 0 -0.018" rpy="0 0 0" />
      <geometry>
	<box size="0.05 ${camera_offset+0.04} 0.013" />
      </geometry>
      <material name="Red"/>
    </visual>
  </xacro:static_transform>

    <xacro:manta_cam_v0 frame_name="${prefix}/left_camera" parent="${prefix}/camera_rail" camera_name="${prefix}/left">
      <origin xyz="0.0 ${camera_offset/2} 0.0" rpy="0 0 0" />
    </xacro:manta_cam_v0> 
    
    <xacro:manta_cam_v0 frame_name="${prefix}/right_camera" parent="${prefix}/camera_rail" camera_name="${prefix}/right">
      <origin xyz="0.0 ${-camera_offset/2} 0.0" rpy="0 0 0" />
    </xacro:manta_cam_v0> 

    <xacro:static_transform parent="${prefix}/camera_rail" name="${prefix}_optical_frame" xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}">
    <visual>
      <geometry>
	<box size="0 0 0" />
      </geometry>
      <material name="Clear">
	<color rgba="0 0 0 0"/>
      </material>
    </visual>
  </xacro:static_transform>

  </xacro:macro>
  
</root>
