"""autogenerated by genpy from OryxMessages/SwervePositions.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SwervePositions(genpy.Message):
  _md5sum = "ce91d1774d95f0a86e888d5fe76a8af6"
  _type = "OryxMessages/SwervePositions"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#Swerve positions, in radians
float64 left_front_wheel
float64 right_front_wheel
float64 left_rear_wheel
float64 right_rear_wheel
"""
  __slots__ = ['left_front_wheel','right_front_wheel','left_rear_wheel','right_rear_wheel']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_front_wheel,right_front_wheel,left_rear_wheel,right_rear_wheel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SwervePositions, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_front_wheel is None:
        self.left_front_wheel = 0.
      if self.right_front_wheel is None:
        self.right_front_wheel = 0.
      if self.left_rear_wheel is None:
        self.left_rear_wheel = 0.
      if self.right_rear_wheel is None:
        self.right_rear_wheel = 0.
    else:
      self.left_front_wheel = 0.
      self.right_front_wheel = 0.
      self.left_rear_wheel = 0.
      self.right_rear_wheel = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.left_front_wheel, _x.right_front_wheel, _x.left_rear_wheel, _x.right_rear_wheel))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.left_front_wheel, _x.right_front_wheel, _x.left_rear_wheel, _x.right_rear_wheel,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.left_front_wheel, _x.right_front_wheel, _x.left_rear_wheel, _x.right_rear_wheel))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.left_front_wheel, _x.right_front_wheel, _x.left_rear_wheel, _x.right_rear_wheel,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
