"""autogenerated by genmsg_py from Temperature.msg. Do not edit."""
import roslib.message
import struct


class Temperature(roslib.message.Message):
  _md5sum = "e62c9d14f34e94252b4cc03e1d4997da"
  _type = "OryxMessages/Temperature"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 temperature_node
float32 temperature
float32 warning_Temp
float32 danger_Temp

"""
  __slots__ = ['temperature_node','temperature','warning_Temp','danger_Temp']
  _slot_types = ['int32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.
    
    The available fields are:
       temperature_node,temperature,warning_Temp,danger_Temp
    
    @param args: complete set of field values, in .msg order
    @param kwds: use keyword arguments corresponding to message field names
    to set specific fields. 
    """
    if args or kwds:
      super(Temperature, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.temperature_node is None:
        self.temperature_node = 0
      if self.temperature is None:
        self.temperature = 0.
      if self.warning_Temp is None:
        self.warning_Temp = 0.
      if self.danger_Temp is None:
        self.danger_Temp = 0.
    else:
      self.temperature_node = 0
      self.temperature = 0.
      self.warning_Temp = 0.
      self.danger_Temp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    @param buff: buffer
    @type  buff: StringIO
    """
    try:
      _x = self
      buff.write(_struct_i3f.pack(_x.temperature_node, _x.temperature, _x.warning_Temp, _x.danger_Temp))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    @param str: byte array of serialized message
    @type  str: str
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.temperature_node, _x.temperature, _x.warning_Temp, _x.danger_Temp,) = _struct_i3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    @param buff: buffer
    @type  buff: StringIO
    @param numpy: numpy python module
    @type  numpy module
    """
    try:
      _x = self
      buff.write(_struct_i3f.pack(_x.temperature_node, _x.temperature, _x.warning_Temp, _x.danger_Temp))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    @param str: byte array of serialized message
    @type  str: str
    @param numpy: numpy python module
    @type  numpy: module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.temperature_node, _x.temperature, _x.warning_Temp, _x.danger_Temp,) = _struct_i3f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise roslib.message.DeserializationError(e) #most likely buffer underfill

_struct_I = roslib.message.struct_I
_struct_i3f = struct.Struct("<i3f")
