; Auto-generated. Do not edit!


(cl:in-package oryx_drive_controller-msg)


;//! \htmlinclude VelocityCommandResult.msg.html

(cl:defclass <VelocityCommandResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil)
   (capable
    :reader capable
    :initarg :capable
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass VelocityCommandResult (<VelocityCommandResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VelocityCommandResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VelocityCommandResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name oryx_drive_controller-msg:<VelocityCommandResult> is deprecated: use oryx_drive_controller-msg:VelocityCommandResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <VelocityCommandResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader oryx_drive_controller-msg:success-val is deprecated.  Use oryx_drive_controller-msg:success instead.")
  (success m))

(cl:ensure-generic-function 'capable-val :lambda-list '(m))
(cl:defmethod capable-val ((m <VelocityCommandResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader oryx_drive_controller-msg:capable-val is deprecated.  Use oryx_drive_controller-msg:capable instead.")
  (capable m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VelocityCommandResult>) ostream)
  "Serializes a message object of type '<VelocityCommandResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'capable) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VelocityCommandResult>) istream)
  "Deserializes a message object of type '<VelocityCommandResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:setf (cl:slot-value msg 'capable) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VelocityCommandResult>)))
  "Returns string type for a message object of type '<VelocityCommandResult>"
  "oryx_drive_controller/VelocityCommandResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VelocityCommandResult)))
  "Returns string type for a message object of type 'VelocityCommandResult"
  "oryx_drive_controller/VelocityCommandResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VelocityCommandResult>)))
  "Returns md5sum for a message object of type '<VelocityCommandResult>"
  "e59ed3dd007d15d0c6611c9efabb1f70")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VelocityCommandResult)))
  "Returns md5sum for a message object of type 'VelocityCommandResult"
  "e59ed3dd007d15d0c6611c9efabb1f70")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VelocityCommandResult>)))
  "Returns full string definition for message of type '<VelocityCommandResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%bool capable~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VelocityCommandResult)))
  "Returns full string definition for message of type 'VelocityCommandResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%bool capable~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VelocityCommandResult>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VelocityCommandResult>))
  "Converts a ROS message object to a list"
  (cl:list 'VelocityCommandResult
    (cl:cons ':success (success msg))
    (cl:cons ':capable (capable msg))
))
