/* Auto-generated by genmsg_cpp for file /home/parallels/fuerte_workspace/oryxssr/action_test/msg/TestGoal.msg */
#ifndef ACTION_TEST_MESSAGE_TESTGOAL_H
#define ACTION_TEST_MESSAGE_TESTGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace action_test
{
template <class ContainerAllocator>
struct TestGoal_ {
  typedef TestGoal_<ContainerAllocator> Type;

  TestGoal_()
  : request(0)
  {
  }

  TestGoal_(const ContainerAllocator& _alloc)
  : request(0)
  {
  }

  typedef int32_t _request_type;
  int32_t request;


  typedef boost::shared_ptr< ::action_test::TestGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_test::TestGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TestGoal
typedef  ::action_test::TestGoal_<std::allocator<void> > TestGoal;

typedef boost::shared_ptr< ::action_test::TestGoal> TestGoalPtr;
typedef boost::shared_ptr< ::action_test::TestGoal const> TestGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::action_test::TestGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::action_test::TestGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace action_test

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::action_test::TestGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::action_test::TestGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::action_test::TestGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "650f0ccd41c8f8d53ada80be6ddde434";
  }

  static const char* value(const  ::action_test::TestGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x650f0ccd41c8f8d5ULL;
  static const uint64_t static_value2 = 0x3ada80be6ddde434ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_test::TestGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "action_test/TestGoal";
  }

  static const char* value(const  ::action_test::TestGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::action_test::TestGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
int32 request\n\
\n\
";
  }

  static const char* value(const  ::action_test::TestGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::action_test::TestGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::action_test::TestGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.request);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TestGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_test::TestGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::action_test::TestGoal_<ContainerAllocator> & v) 
  {
    s << indent << "request: ";
    Printer<int32_t>::stream(s, indent + "  ", v.request);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACTION_TEST_MESSAGE_TESTGOAL_H

